package mcp

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"testing"
)

// TestToolSchemaLock_PerTool locks the per-tool wire-protocol schema:
// name + description + input schema + output schema + annotations. It
// extends TestToolSurfaceLock_Names (which only locks tool *names*) by
// catching the "schema drift" failure mode flagged in
// .research/residual-literal-100-engineering-path.md item #4 and the
// integration audit Phase 4: a tool description or input-schema change
// that breaks downstream LLM tool-router caches without triggering the
// name-set lock.
//
// Hashing strategy:
//
//   - For each tool, call its mcp.Tool.MarshalJSON(). The mcp-go library
//     guarantees stable JSON output (sorted property keys, deterministic
//     enum ordering) — see mcp.Tool.MarshalJSON in mcp-go v0.46.0.
//   - Hash that JSON via SHA256 to produce a per-tool schema hash.
//   - Compute a rollup hash over the sorted "name:hash" lines for a
//     single golden value.
//
// On mismatch, the failure log lists per-tool drift: which tool's
// schema changed and what the new hash is. This makes it trivial for
// reviewers to identify accidental description churn (which silently
// invalidates tool-router caches in Claude Desktop / Cursor / etc.)
// vs intentional schema evolution (where the lock is updated as part
// of the same PR).
//
// HOW TO UPDATE:
//
//  1. Run go test ./mcp/ -run TestToolSchemaLock_PerTool to see the
//     drift report.
//  2. If the change is intentional, run scripts/regenerate_tool_schema_hashes.sh
//     to refresh expectedToolSchemaHash + lockedToolSchemaHashes.
//  3. Reviewers must treat the diff as a wire-protocol change and
//     check the per-tool delta.
func TestToolSchemaLock_PerTool(t *testing.T) {
	t.Parallel()

	tools := GetAllTools()
	perToolHashes := make(map[string]string, len(tools))

	for _, tl := range tools {
		spec := tl.Tool()
		// MarshalJSON is the canonical wire shape an MCP client sees in
		// tools/list — the most accurate proxy for "did the contract
		// the client binds to change?".
		blob, err := json.Marshal(spec)
		if err != nil {
			t.Fatalf("tool %q failed to marshal: %v", spec.Name, err)
		}
		h := sha256.Sum256(blob)
		perToolHashes[spec.Name] = hex.EncodeToString(h[:])
	}

	// Sort name:hash pairs for the rollup.
	pairs := make([]string, 0, len(perToolHashes))
	for name, hash := range perToolHashes {
		pairs = append(pairs, name+":"+hash)
	}
	sort.Strings(pairs)

	rollup := sha256.Sum256([]byte(strings.Join(pairs, "\n")))
	gotRollup := hex.EncodeToString(rollup[:])

	if gotRollup == expectedToolSchemaHash {
		return
	}

	// Drift report — figure out per-tool what changed.
	expectedMap := make(map[string]string, len(lockedToolSchemaHashes))
	for _, line := range lockedToolSchemaHashes {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		name, hash, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		expectedMap[name] = hash
	}

	var added, removed, changed []string
	for name, gotHash := range perToolHashes {
		expHash, ok := expectedMap[name]
		switch {
		case !ok:
			added = append(added, fmt.Sprintf("%s (hash=%s)", name, gotHash))
		case expHash != gotHash:
			changed = append(changed, fmt.Sprintf("%s (was=%s now=%s)", name, expHash, gotHash))
		}
	}
	for name := range expectedMap {
		if _, ok := perToolHashes[name]; !ok {
			removed = append(removed, name)
		}
	}
	sort.Strings(added)
	sort.Strings(removed)
	sort.Strings(changed)

	// Build a "full new lock" block — every current tool, sorted, on its
	// own GOLDEN<...>GOLDEN-tagged line for the regenerate script to grep.
	goldenLines := make([]string, 0, len(perToolHashes))
	for _, p := range pairs {
		goldenLines = append(goldenLines, "GOLDEN<"+p+">GOLDEN")
	}

	t.Errorf("tool schema drift detected.\n  expected rollup: %s\n  actual rollup:   %s\n  added:    %s\n  removed:  %s\n  changed:  %s\n\nFull new lock (one per tool, GOLDEN-tagged for the regenerate script):\n%s\n\nUpdate expectedToolSchemaHash + lockedToolSchemaHashes (see scripts/regenerate_tool_schema_hashes.sh).",
		expectedToolSchemaHash, gotRollup,
		strings.Join(added, "\n            "),
		strings.Join(removed, ", "),
		strings.Join(changed, "\n            "),
		strings.Join(goldenLines, "\n"))
}

// expectedToolSchemaHash is SHA256 over strings.Join(sortedNameHashPairs, "\n")
// where each pair is "<name>:<sha256(MarshalJSON(spec))>".
//
// Generated by scripts/regenerate_tool_schema_hashes.sh.
const expectedToolSchemaHash = "c56703dc90ff175d17d74518d2a23c607274e967a37c0899be5b16f29ba647d0"

// lockedToolSchemaHashes is the per-tool golden table — used only for
// diff-on-mismatch reporting. One entry per registered MCP tool, in the
// form "<tool_name>:<hex sha256 of MarshalJSON(spec)>".
//
// Generated by scripts/regenerate_tool_schema_hashes.sh.
var lockedToolSchemaHashes = []string{
	"add_to_watchlist:300d9c4558e8dc398bf20746c7ea9467469178f5c445884c8d67aa68530d39bd",
	"admin_activate_user:6fb13d08a1d759d7667b1b1117812144004866db158a03028bcedb813237d943",
	"admin_change_role:7bee26026bc6fd80867fa0d0ac4c5bab95b03719f825b603bff06cf398e0376d",
	"admin_freeze_global:e6804e006f24c61650a4e468f1ed07d976e742dd33f5ad94391d1fd40e23140e",
	"admin_freeze_user:4ffe198c97bc1736027faa68b989e0a31c35fd1870a120862a0f044df4ba4571",
	"admin_get_risk_status:63c2849d1ecb32bd46bd2330e8dfec7eed9c182221670ab35c9a4b86b79ac18e",
	"admin_get_user:b0bf5d65c2dfdb1b0949cc89f875f2dd42ec906096727f56b5d5de6adb1267a8",
	"admin_get_user_baseline:f4da5b3685cd6cec14d42bf432a4d3bf614905b4e511c81f4a1bb9f9d2060b1e",
	"admin_invite_family_member:128751c538b6e5a97a8c64cf78bec9f9037610dddfc76257223ab428d71c94cb",
	"admin_list_anomaly_flags:2c33cd275b488b32c58bc7effbbf12c5ae5e4dd4d759c76e5ff5a28552968487",
	"admin_list_family:41097483c2105e4eac0f1e00fee2f5cba5add36db6a71b9ad75d88e8f1a95266",
	"admin_list_users:154a689b6f06efa0d7ff00eb5d8384f9949b46fc9dbbdd1aaf19683824aea670",
	"admin_remove_family_member:086c197f34c12a9a582862198d5020ceecc12ab2d90b2b997c76f8449fa646d0",
	"admin_server_status:391930e3f0dad0fa522b8825d6d7302bff506d5d327bb4c5b4b5d416ce0c9235",
	"admin_set_billing_tier:b9de7aaf8debb929bcf0be49a100659851beace9dc9c23c6e62495d8d511ef57",
	"admin_stats_cache_info:96a7fb1b43e65456bb821f69181ff1b68d2e7b81abe27d5a89873a08f3fb51b7",
	"admin_suspend_user:d0bf946ae888951337a7ca5d36699e160ff84683d65b94cafff6978ced6d67b8",
	"admin_unfreeze_global:1ee61d720e7e4d3d56ae3906a9f10d747ea8eeb95f3134f4089fddc25134a291",
	"admin_unfreeze_user:f67e3675a7fd97015c490a70d55ea669bc322d59c97647c60ad6014020c1e1e7",
	"analyze_concall:75e27082f297e0a5b3e7370393809a9ac5171cf7447e1e076302e51ef9f6449a",
	"cancel_mf_order:d871484b1f9ff748b4c303f0ba59809f61d058ca44d0857d8d46779b3230585c",
	"cancel_mf_sip:6e8298102a534166e3e19697db59867bcda65dd9449cb678f7772265aad9ca9f",
	"cancel_order:91548b2a487c3a26eab72c7a5a598beaa442e7da1e23d0e1cd3058a2f577a31c",
	"cancel_trailing_stop:8e82e8ff34f918b841594a92c2be3a1976cc3c3d14288052d9e677d2fbc51502",
	"close_all_positions:a4105c0156e55f9ba30e876954ce0d9231455a51bc9c7da8d40b2a6d39fcc62f",
	"close_position:52b64486a5d67effd0082891673677f7d191e4c085d618e14c186e6e55c075ae",
	"composite_alert:1fd2abefa481ecb5d13f697dcdedda1f89d85b5efea3cf5ba567b24a08448b99",
	"convert_position:dcc8be3cba7955e6c2e6b68e188b00874835056f313442e7075c2ec383ca646e",
	"create_watchlist:3b46ee64e1f825436a3dc8e9ff2db3faee3710ec10789e858d2e380276751b09",
	"delete_alert:7e87ea15745e03b9532e7887e3cc73345f3d50d3c2c13dda49167b91707bf362",
	"delete_gtt_order:ab8f65d9e25d0c2a39513aa8a91b86acd2373e423a724db90917c3a3e0784e4c",
	"delete_my_account:3a435e84692a99f75686255c6c1f719b1a0ab56658086547b572f7c495d0fb95",
	"delete_native_alert:23773d76ed56fb802fb77816f53ca11f731d8a0e86022f52a803b3cdf01cd8af",
	"delete_watchlist:8cc2614570ea192df3f18863fe2d640b13518357aaa509f6b6747cf99855f096",
	"dividend_calendar:d5e0621058b8d0f299407d04b1022e22795b4cb297e287e9ac4656e19e4fae20",
	"get_alert_history_reconstituted:2d89d1808f0135a7a34c74cf7097107d9023fcb390bc59a6fd996af51d91d75a",
	"get_basket_margins:937dfb4e6fae15cedf6970fe87214ae5a65dccc6762ee86483394512b341f181",
	"get_fii_dii_flow:845be727e3bbd8436d47f3ff9f3db2a476a00469e9ded453a3c06ac7e1aff8e5",
	"get_gtts:c0bf5a0d4c5ddd0dbcd30e3b97a97c9e5d45d22e7d9af5bcf2fdd1109cbe7516",
	"get_historical_data:56899d8ad8320b985b7ec187382f2586058769476273d95a707d08fba8856eba",
	"get_holdings:98383cdae2b8c667df6a5aac8c029feae445f0c9eab3cc0ffd9ac2d6ad7a58ec",
	"get_ltp:160116d0313d2579a95863696b9ad23398ee24098add1c2432be4db5b2d30269",
	"get_margins:e5c67f1d77844761377835de8f46490b640c47ee4e33639a6ef53fe4aa10c1ad",
	"get_mf_holdings:36feb07171d39a0dc5a93c1ae65f0adaa403331d0644ce7f66eb9d531a76f41d",
	"get_mf_orders:f6a91d33c1a9cb44f4540d87f9844c376e8777f47df3de9ac44a5fe76ce65b8c",
	"get_mf_sips:1927c29946bb9b6cc4f55e45090c4a893be6e57a42698c27f5491f812baa31f7",
	"get_native_alert_history:0cc5186881121ccd21a088dd3d29915cc48632c59e58b56c5ea74ab1916a8c4d",
	"get_ohlc:9b3e5a63a191dacbc87fe650052f87dcac5da046e83ad0c189ee509adb74eaa0",
	"get_option_chain:86280ff1761523a19abfde49aab42b37152f9944eca61988538edce08fb08b2e",
	"get_order_charges:2ba0da33125965e15fbf39ea349302e2907d4e237cf6e9b9ae30a1b96d462a7c",
	"get_order_history:a14c3ee46b6cfadce8b3a2db5e32f494d0b6f20d171c3c33de42e37833a07361",
	"get_order_history_reconstituted:fe42457b13cf205a029e68bb38d6e9a5ffd421417ff42fe2f197bf47b4e877f2",
	"get_order_margins:5a6d54b5a78b404d25647dd2a2aa09bc7c77e6d793d4905b6e6bffd751a29b94",
	"get_order_projection:952df4f4fb1054d2276b38bec0c8537843632209aa9e178ae795f1f4b5711fe7",
	"get_order_trades:fbd502b6b1425bd63a329e6b63d5152ba68b9af8b2969d11bd922605aaabb599",
	"get_orders:d716025257d0a9813293059f8c755f6e6d2d10ba60950fb7b3e3c7ce9b7a3e5f",
	"get_pnl_journal:806b1180785f23c774ce69de10b014cf6f557f3e7de2175634dd35ba23c8847b",
	"get_position_history_reconstituted:e10c14b6c5f8658de52a8e989870174e23b68e66f7698bf70ce753638f75b6ff",
	"get_positions:2413c3057df6f7dd6638da2f0c1cdd45e078e025f83968036bcb723933a5ed92",
	"get_profile:54cb1849caff547b0a335b939d5e2266122a86d33cac391931cfd5ee062244ef",
	"get_quotes:9d9119c662b1ab87758ba704cb3a1ff661aef071c80512193d9d3fb44a31125d",
	"get_trades:5cc8bf166d05b040c1ad86c6991627b3ad14ff3c5ad5f4d888a8393b936e693b",
	"get_watchlist:6e1eba6cdfe94a1f891bcfc7d58c1d9d2ee2a563a3eae937f677c94e82bbcb0c",
	"historical_price_analyzer:42ef6e6aa3a05ad9653721547dabf0ceab184a8adfd774e34be1a49f2b4f2dc5",
	"list_alerts:b315c2f46478b98ddba83595be997daa80c47cd4f7850a566b4c6e7fc1b94e3a",
	"list_mcp_sessions:340d029b7c381d93d97c005a6a8df5e642614ba202578c7c2f4b41e8ff4ab62c",
	"list_native_alerts:fbfedcf410266d53013c72cbbd372b680288db59e0c45cd421ff1461d23fd3e1",
	"list_trailing_stops:385ab141407405540104d7c0033ef8050eefca3b5a97ba4cd758f1885834f66f",
	"list_watchlists:1e5841dcb88bf61ce81366c5e0e4b2bc50958d26f7efff6a3e0932083aee8d26",
	"login:0cc25e857640db710a0ea6073d6224b32eaaf48fae6d5a67d824cf562b767fa4",
	"modify_gtt_order:96c5cc700c5599339a6ec1eec73a6cc4f0047c24807d3467dbaa86a1011ac7d5",
	"modify_native_alert:c31f142259c6f446f0bdd1273aaba4f52ec5756b88ec73866206c3d80ac4dec7",
	"modify_order:cf9182f6dee39dd8cf6c2617aaa53572de5327437ee0fbd2d4891e0ffb7ad851",
	"open_dashboard:da0e32cac41b3a9a6944ed487df43653c7fcadc7457253bcb291684c2c1e5ea3",
	"options_greeks:6419745a07e576bc7bf1666e36f726a60c9c5e30f6ba2e4eb8c19b0e07bc2c59",
	"options_payoff_builder:f83db925063024aeed784944289774943f9f13aa8d64af5b1362ca9e6ef80cb7",
	"order_risk_report:9de6ebaf16a192b48a2c1b950e13b1aa9effc2e4e0db4a2922d8e3fdaa57e765",
	"paper_trading_reset:0d4d966f819cb1da18a9e042fcec4ae8f147b8581f51ddf9af662c816da6e71d",
	"paper_trading_status:aad822b9e25ac2bf57969c17bfd52df3e15406577791923ee3ea1b4c3b565242",
	"paper_trading_toggle:32dfdfd0c4be273795c424ff8b78648289c98741a7fd1b6337a4b8614299e67b",
	"peer_compare:fffd0264ad80cc87d46154e45f53016bf69086db591c0d587fa1e9c5b4c7b87c",
	"place_gtt_order:1652efbd3b773691227bb5c9e66ca28551d097d3137eda28950ed11ac3cecd78",
	"place_mf_order:1cba17f4189784bfb8597e14ccd06b1c52f22d22053b4ed0798761230325587b",
	"place_mf_sip:83c5d3266c7c57ebf298e5726f40d8b5764d9bbfba587bc9178b7984ca8b3612",
	"place_native_alert:ac2278033d3036d8dd9f2ebcc97db7e0a74bd004e42594e9183aedf4f7409595",
	"place_order:513f44552c14a5c1b48d7923085593cbcdb0f2b8d25a5d4e052be4491c0b0496",
	"portfolio_analysis:c8b7a3eca318a25d068492287d316a1b0074717c286227ea239f089a8dcfd291",
	"portfolio_concentration:f8ae046d4a601434dd966c3a56cb7b388526e0205f253505f8e0a6baa080b67c",
	"portfolio_summary:61b60c793b34331ebb1eaa65dbf71cfa8f854a62560b60cb9996884a4b9198f4",
	"position_analysis:dda97dcb334bdec8fd7aee6bcd66668cfa5f2d3dd0075c22e78693207ab32b02",
	"remove_from_watchlist:9f1dcfc3df303482c986b5db6a2843db651616a70e7240d8d4fce7a04c32c318",
	"revoke_mcp_session:0048ec0e39c156b718fea342e1eac157905db35f650dd2ca76f142f872a94bd0",
	"search_instruments:c14984460c1ebb4057717e13c0fd2d3638f0e8b0d6ae34d94068182a07f8d570",
	"sebi_compliance_status:286a5e4789619115fa6d62789c627fd4e009403257203a49ff68d39a829b985e",
	"sector_exposure:1cb8e963490fb8aad45c65bf7289c699c06f28586362b9a6582b2e7ee26a01dc",
	"server_metrics:9277f31ca08304f14ccaee7326365772ac1b9483c3551487a180419b4de6bf23",
	"server_version:b321bd6d8fd15453475266e5de808cb6f07fb1dc1391343fd4b4ed677938eaa3",
	"set_alert:29a0daa26282be07ebd70de3865307df03afd3ab45ad3bc445598abaec5bcc56",
	"set_trailing_stop:5262791726254785cbd683b30162b2cde5b2f38a7f0d11a08935b5d6e440ec5a",
	"setup_telegram:d9fe6eaa360edde6c4def108006022042f3fdd64dde17edb0197a1466e976d8e",
	"start_ticker:4bb1f2ea1be839fa5dff486a7af3ba6aa2d6e9120bab4f811bea2bd1c0facf69",
	"stop_ticker:44fa11ac84e0c01944f8aa43fdde61ac0cb74336b0df66fba134d6eba0b2e50d",
	"subscribe_instruments:385f56d4a03d962d19bf2c8528b7dd54a820a5e6b2abadd25cfad7ba308ebf6b",
	"tax_loss_analysis:066e6c351f226d45c7678b82af6c6d15a81c16b65ae1d8ede541582f015955be",
	"technical_indicators:675299a268febfd379c2726e60c17b7f6e1ebd801b0f01b15e81ca5782fef44f",
	"test_ip_whitelist:8253cd1ae1463db0bf103bf068ef2536f62220dd32741d81f2a24ab26351b49d",
	"ticker_status:479a2a5175d5a9fb906a68d9b6ab5ca0a59b59b8bfba82ce742aa1eb54541a90",
	"trading_context:b890bc891167399a1e8c0543d5aa103b48d466f6f32b8ca594a25dcd3324ce87",
	"unsubscribe_instruments:165091c36f8182a035e3ee963ef4b3065032ef43cab531146713e7a229a0930e",
	"update_my_credentials:2baef35f9b61a46c6c1f2f1f0307c075aeb0a1bc04d9fad7ae32129c79c5ec5b",
	"volume_spike_detector:2c793f4444e0fa205b2eebf603af544853803a196f24af0edabc8f270bbd9636",
}
